[project]
name = "banking-complaints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.0",
    "mcp[cli]>=1.2.0",
    "python-dateutil>=2.9.0",
]
