#!/usr/bin/env node
/* eslint-disable no-console */
const path = require('path');
const fs = require('fs/promises');
const { existsSync } = require('fs');

async function main() {
  const [, , rawName] = process.argv;
  if (!rawName) {
    console.error('Usage: node scripts/scaffolding/create-module.js <layer/path>');
    process.exit(1);
  }

  const rootDir = path.resolve(__dirname, '../..');
  const targetDir = path.join(rootDir, 'src', rawName);

  if (existsSync(targetDir)) {
    console.error(`Module "${rawName}" already exists at ${targetDir}`);
    process.exit(1);
  }

  await fs.mkdir(targetDir, { recursive: true });

  const moduleName = rawName.split('/').pop();
  const indexPath = path.join(targetDir, 'index.ts');
  const readmePath = path.join(targetDir, 'README.md');

  const moduleJsonPath = path.join(targetDir, 'module.json');
  const manifest = {
    id: rawName,
    name: moduleName,
    entry: './index.ts',
    version: '0.1.0',
  };

  const template = `// ${moduleName} module scaffold generated by create-module.js\nexport interface ${pascalCase(
    moduleName,
  )}Options {\n  // TODO: define module options\n}\n\nexport function create${pascalCase(
    moduleName,
  )}(/* options: ${pascalCase(
    moduleName,
  )}Options */) {\n  // TODO: implement module\n  return {};\n}\n`;

  await fs.writeFile(indexPath, template, 'utf8');
  await fs.writeFile(
    readmePath,
    `# ${moduleName}\n\nThis module was generated via \`scripts/scaffolding/create-module.js\`.\n\n- **Path:** ${rawName}\n- **Entry:** \`index.ts\`\n\nFill in the implementation details and add tests in \`tests/\`.\n`,
    'utf8',
  );
  await fs.writeFile(moduleJsonPath, JSON.stringify(manifest, null, 2), 'utf8');

  console.log(`Module created at ${targetDir}`);
}

function pascalCase(value) {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1))
    .join('');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
